server {
	listen 80;
	server_name todo.glacial.site;
	
	location / {
		root /usr/share/nginx/html;
		index index.html index.htm;
		try_files $uri $uri/ /index.html;
	}
}

server {
	listen 80;
	server_name todolistplusplus-server.glacial.site;

	location / {
		proxy_pass http://todolist-backend:3000;
		proxy_set_header Host $host;
	}
}